version: '3.1'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 8888:27017
  todo:
    container_name: todo
    image: todo
    ports:
      - 5000:5000
    environment:
      - MONGODB_URL=mongodb://mongo:8888/todo-app

#     networks:
#      - devops_default
# networks:
#   devops_default:
#     external: true
