version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    # networks:
    #  - devops_default
  todo:
    image: todo
    ports:
     - "3000:3000"
    environment: 
     - MONGODB_URL="mongodb://mongo:27017/todo-app"
#     networks:
#      - devops_default
# networks:
#   devops_default:
#     external: true
