version: '3.1'
services:
  mongo:
    container_name: mongopublic
    image: mongo
    restart: always
    ports:
      - 27017:27017
  todo:
    container_name: todopublic
    image: todo
    ports:
      - 3000:3000
    environment:
      - MONGODB_URL=mongodb://mongopublic:27017/todo-app

#     networks:
#      - devops_default
# networks:
#   devops_default:
#     external: true
